apiVersion: v1
kind: Service
metadata:
  name: voting-service1
  labels:
    name: voting-service1
    app: demo-voting-app1
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: voting-app-pod1
     app: demo-voting-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod1
      app: demo-voting-app1
  template:
    metadata:
      name: voting-app-pod1
      labels:
        name: voting-app-pod1
        app: demo-voting-app1

    spec:
      containers:
      - name: voting-app1
        image: cooldsachin/reactjs
        imagePullPolicy: Always
        ports:
        - containerPort: 80
